server:
  port: 8081

url:
  payment: "http://payment"

spring:
  application:
    name: order
  # Spring CLoud Consul 配置
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true