server:
  port: 8080

spring:
  application:
    name: payment
  datasource:
    url: jdbc:mysql://localhost:3306/Spring-Cloud
    username: root
    password: 19960214At313!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    #    多环境设置，dev，default，production, test， 默认 default
    active: dev